### ISSUE TITLE
retron needs to upload the page or upload it on chat.wgyt.yk

### ISSUE THREAD

**Issue by wgyt** [wgytwebsites/website-contest#1]
@YOYITsM3M8 look at the above

**Comment by YOYITsM3M8** [comment]
Umm

**Comment by YOYITsM3M8** [comment]
You want me to actually put your address on the page?

**Comment by wgyt** [comment]
> You want me to actually put your address on the page?

just hide it for now because who knows 🤷🏻

**Comment by wgyt** [comment]
@YOYITsM3M8 what is the src code for the website? Could you upload it here?

**Comment by YOYITsM3M8** [comment]
> @YOYITsM3M8 what is the src code for the website? Could you upload it here or in a fork?

I sent it on disc

**Comment by wgyt** [comment]
> > @YOYITsM3M8 what is the src code for the website? Could you upload it here or in a fork?
> 
> I sent it on disc

ok

**Comment by wgyt** [comment]
![Screenshot 2021-01-18 at 14 42 29](https://user-images.githubusercontent.com/68466727/104957068-730d8180-599b-11eb-85e1-cc3e626738d0.png)
@YOYITsM3M8 ^^^
